### ISSUE TITLE
Add basic controller structure

### ISSUE THREAD

**Issue by maruina** [Skyscanner/argocd-progressive-rollout#7]
Create the basic structure of the controller with a basic CRD. A basic CRD looks like

```
apiVersion: deployment.skyscanner.net/v1alpha1
kind: ProgressiveRollout
metadata:
  name: myservice
  namespace: argocd
spec:
  sourceRef:
    apiGroup: argoproj.io/v1alpha1
    kind: ApplicationSet
    name: file-cache-proxy
  stages:
    - name: one cell as canary in eu-west-1
      maxParallel: 1 # can be omitted as default is 1
      maxTargets: 1
      targets:
        clusters:
          selector:
            matchLabels:
              region: eu-west-1
```

The cluster selection logic should be on a different PR.
The CRD status looks like

```
status:
  conditions:
    - lastTransitionTime: "2019-07-10T08:23:18Z"
      lastUpdateTime: "2019-07-10T08:23:18Z"
      message: Progressive rollout completed successfully, rollout finished.
      reason: Succeeded
      status: "True"
      type: RolledOut
```

When creating a ProgressiveRollout object, the controller should reconcile and just succeed.

## TODO

[ ] Tests
[ ] Update README with CRD specs
