### ISSUE TITLE
Add stage status

### ISSUE THREAD

**Issue by maruina** [Skyscanner/argocd-progressive-rollout#8]
We should provide users with a feedback about not only the ProgressiveRollout CRD itself, but about each of its stages.

A `status.stages` should look like

```
status:
  stages:
    - name: canary in emea
      phase: Completed
      message: Stage completed
      startedAt: 2019-07-10T08:23:18Z
      finishedAt: 2019-07-10T08:40:18Z
    - [...]
```
